# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  registry:
    image: registry:2.8.1
    restart: unless-stopped
    volumes:
      - registry_data:/var/lib/registry
    networks:
      registry:
    deploy:
      resources:
        limits:
          memory: 0.5gb

volumes: 
  registry_data:

networks:
  registry:
